#spring:
#? profiles:
#??? active:
#  ??? - dev
#---
#spring:
#? profiles: dev?????#
#  ? application:?
#??? name: microservicecloud-config-atguigu-dev
#---
#spring:
#? profiles: test?? #Ի
#  ? application:?
#??? name: microservicecloud-config-atguigu-test
##??뱣ΪUTF-8ʽ
#  ?
spring:
  profiles:
    active: dev

---
spring:
? profiles: dev
  ? application: ?
??? name: springcloud-config-atguigu-dev
---
spring:
? profiles: test??
  ? application: ?
??? name: springcloud-config-atguigu-test